package beans;
// Generated May 12, 2019 7:49:38 PM by Hibernate Tools 4.3.1



/**
 * InvigilatorDetails generated by hbm2java
 */
public class Invigilator_details  implements java.io.Serializable {


     private String invigilatorId;
     private String invigilatorPassword;
     private String invigilatorName;
     private String invigilatorBase;
     private Integer department;
     private String designation;
     private String allowanceKey;
     private String emailId;
     private long contactNumber;
     private String qualification;
     private String experience;
     private String specializedSubject1;
     private String specializedSubject2;
     private String specializedSubject3;
     private String specializedSubject4;
     private String address;

    public Invigilator_details() {
    }

	
    public Invigilator_details(String invigilatorId, String invigilatorBase, String emailId, long contactNumber, String qualification, String experience, String specializedSubject1, String specializedSubject2, String specializedSubject3, String specializedSubject4, String address) {
        this.invigilatorId = invigilatorId;
        this.invigilatorBase = invigilatorBase;
        this.emailId = emailId;
        this.contactNumber = contactNumber;
        this.qualification = qualification;
        this.experience = experience;
        this.specializedSubject1 = specializedSubject1;
        this.specializedSubject2 = specializedSubject2;
        this.specializedSubject3 = specializedSubject3;
        this.specializedSubject4 = specializedSubject4;
        this.address = address;
    }
    public Invigilator_details(String invigilatorId, String invigilatorPassword, String invigilatorName, String invigilatorBase, Integer department, String designation, String allowanceKey, String emailId, long contactNumber, String qualification, String experience, String specializedSubject1, String specializedSubject2, String specializedSubject3, String specializedSubject4, String address) {
       this.invigilatorId = invigilatorId;
       this.invigilatorPassword = invigilatorPassword;
       this.invigilatorName = invigilatorName;
       this.invigilatorBase = invigilatorBase;
       this.department = department;
       this.designation = designation;
       this.allowanceKey = allowanceKey;
       this.emailId = emailId;
       this.contactNumber = contactNumber;
       this.qualification = qualification;
       this.experience = experience;
       this.specializedSubject1 = specializedSubject1;
       this.specializedSubject2 = specializedSubject2;
       this.specializedSubject3 = specializedSubject3;
       this.specializedSubject4 = specializedSubject4;
       this.address = address;
    }
   
    public String getInvigilatorId() {
        return this.invigilatorId;
    }
    
    public void setInvigilatorId(String invigilatorId) {
        this.invigilatorId = invigilatorId;
    }
    public String getInvigilatorPassword() {
        return this.invigilatorPassword;
    }
    
    public void setInvigilatorPassword(String invigilatorPassword) {
        this.invigilatorPassword = invigilatorPassword;
    }
    public String getInvigilatorName() {
        return this.invigilatorName;
    }
    
    public void setInvigilatorName(String invigilatorName) {
        this.invigilatorName = invigilatorName;
    }
    public String getInvigilatorBase() {
        return this.invigilatorBase;
    }
    
    public void setInvigilatorBase(String invigilatorBase) {
        this.invigilatorBase = invigilatorBase;
    }
    public Integer getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Integer department) {
        this.department = department;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getAllowanceKey() {
        return this.allowanceKey;
    }
    
    public void setAllowanceKey(String allowanceKey) {
        this.allowanceKey = allowanceKey;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public long getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(long contactNumber) {
        this.contactNumber = contactNumber;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getExperience() {
        return this.experience;
    }
    
    public void setExperience(String experience) {
        this.experience = experience;
    }
    public String getSpecializedSubject1() {
        return this.specializedSubject1;
    }
    
    public void setSpecializedSubject1(String specializedSubject1) {
        this.specializedSubject1 = specializedSubject1;
    }
    public String getSpecializedSubject2() {
        return this.specializedSubject2;
    }
    
    public void setSpecializedSubject2(String specializedSubject2) {
        this.specializedSubject2 = specializedSubject2;
    }
    public String getSpecializedSubject3() {
        return this.specializedSubject3;
    }
    
    public void setSpecializedSubject3(String specializedSubject3) {
        this.specializedSubject3 = specializedSubject3;
    }
    public String getSpecializedSubject4() {
        return this.specializedSubject4;
    }
    
    public void setSpecializedSubject4(String specializedSubject4) {
        this.specializedSubject4 = specializedSubject4;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


