package beans;
// Generated May 12, 2019 7:49:38 PM by Hibernate Tools 4.3.1



/**
 * MarkSheets generated by hbm2java
 */
public class MarkSheets  implements java.io.Serializable {


     private int markSheetNumber;
     private String courseCode;
     private String examinationScheme;
     private int department;
     private String invigilatorAssigned;
     private String examination;
     private String confirmation;

    public MarkSheets() {
    }

	
    public MarkSheets(int markSheetNumber, int department) {
        this.markSheetNumber = markSheetNumber;
        this.department = department;
    }
    public MarkSheets(int markSheetNumber, String courseCode, String examinationScheme, int department, String invigilatorAssigned, String examination, String confirmation) {
       this.markSheetNumber = markSheetNumber;
       this.courseCode = courseCode;
       this.examinationScheme = examinationScheme;
       this.department = department;
       this.invigilatorAssigned = invigilatorAssigned;
       this.examination = examination;
       this.confirmation = confirmation;
    }
   
    public int getMarkSheetNumber() {
        return this.markSheetNumber;
    }
    
    public void setMarkSheetNumber(int markSheetNumber) {
        this.markSheetNumber = markSheetNumber;
    }
    public String getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }
    public String getExaminationScheme() {
        return this.examinationScheme;
    }
    
    public void setExaminationScheme(String examinationScheme) {
        this.examinationScheme = examinationScheme;
    }
    public int getDepartment() {
        return this.department;
    }
    
    public void setDepartment(int department) {
        this.department = department;
    }
    public String getInvigilatorAssigned() {
        return this.invigilatorAssigned;
    }
    
    public void setInvigilatorAssigned(String invigilatorAssigned) {
        this.invigilatorAssigned = invigilatorAssigned;
    }
    public String getExamination() {
        return this.examination;
    }
    
    public void setExamination(String examination) {
        this.examination = examination;
    }
    public String getConfirmation() {
        return this.confirmation;
    }
    
    public void setConfirmation(String confirmation) {
        this.confirmation = confirmation;
    }




}


